<?php

namespace GestHouseBundle\Repository;

/**
 * BedroomsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BedroomsRepository extends \Doctrine\ORM\EntityRepository
{
}
