<?php

namespace GestHouseBundle\Repository;

/**
 * townRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class townRepository extends \Doctrine\ORM\EntityRepository
{
}
